version: "3.9"

services:
  database_speedy:
    image: postgres
    container_name: database_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passw
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: template_api
    restart: always
    ports:
      - 3003:3003
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_api
    depends_on:
      - database_api
volumes:
  pgdata:
    driver: local
